/* structure-core.js - Radar 17-H section 1b: structural discovery fallback (assessment "Radar Assessment - Astra Rejected-Population Audit - 2026-09-26", R2-R4).
 * GENERATED by radar_tools/gen-structure-core.py from channel-core.js (detectChannelResearch, sha1 of the copied text 089941eefa1e9cece82bf8b172572a929508b1ab); do not hand-edit.
 * detectStructure(candles, meta[, out]) is detectChannel's RESEARCH pair search with ONE difference: the `position > 0.75` cap is removed (it survives only behind the test flag meta._capPosition,
 * which the drift-guard test uses to prove the copy reproduces detectChannel exactly). Same anchor spacing, wedge, touch, containment gate, lifecycle, scoring and winner selection.
 * Called by capture.js ONLY when detectChannel returned null. A structural fit is context (a channel that exists but is not tradable now); no forward module, episode, order, runner or
 * challenger predicate ever reads it. Loaded by capture.js (require) and radar.html (script tag after channel-core.js; the channel-core names are read from the page globals). */
(function (root, factory) {
  var CCN = ['DETECTOR_VERSION', 'D_AGE_MAX', 'D_AGE_RANGE', 'D_AGE_RANGE_GRID', 'D_BREAK_PENALTY', 'D_CONT_GATE', 'D_CONT_MAX', 'D_EMA_SLOPE_BARS', 'D_EMA_SLOPE_BONUS', 'D_PATTERN_MAX', 'D_POS_FULL_CAP', 'D_POS_MULT', 'D_POS_PTS', 'D_RAW_MAX', 'D_RES_PARALLEL_MAX', 'D_RES_PTS', 'D_TOUCH_PTS', 'D_VOL_TOUCH_BONUS', 'D_VOL_TOUCH_MULT', 'D_VOL_WINDOW', 'D_WIDTH_FRAC', 'D_WIDTH_PENALTY', 'F3_RAIL_UNCHANGED_PCT', 'FIT_SCHEMA_VERSION', 'FIT_WINDOW', 'FIT_WINDOW_GRID', 'MIN_ANCHOR_SPAN', 'MIN_ANCHOR_SPAN_GRID', 'MIN_TOUCH_GAP', 'RECLAIM_BARS', 'RES_RECENT_BARS', 'RES_RECENT_BARS_GRID', 'WEDGE_LOOKAHEAD', 'WEDGE_LOOKAHEAD_GRID', 'applyWickClip', 'atr14', 'bb3Reversion', 'bb3UpperReversion', 'buildPatternRecords', 'bullEngulfing', 'bullEngulfingResearch', 'clamp', 'computeLifecycle', 'computeRecentContainment', 'computeResearchTol', 'detectChannel', 'emaLast', 'emaState', 'entryEconomicsOf', 'executionContextOf', 'findPivotsWindowed', 'fitIndependentResistance', 'isWedge', 'makeFitId', 'multiSignalOnOneCandle', 'passesAnchorSpacing', 'railAt', 'rocketAtSupportResearch', 'scanBreaks', 'signalConflict', 'threeInsideDown', 'threeInsideUp', 'threeInsideUpResearch'];
  var cc;
  if (typeof module === 'object' && module.exports) cc = require('./channel-core.js');
  else { cc = {}; CCN.forEach(function (n) { cc[n] = root[n]; }); }
  var api = factory(cc, CCN);
  if (typeof module === 'object' && module.exports) module.exports = api; else root.StructureCore = api;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this), function (CC, CCN) {
  CCN.forEach(function (n) { if (typeof CC[n] === 'undefined') throw new Error('structure-core: channel-core symbol missing: ' + n); });
  var DETECTOR_VERSION = CC.DETECTOR_VERSION;
  var D_AGE_MAX = CC.D_AGE_MAX;
  var D_AGE_RANGE = CC.D_AGE_RANGE;
  var D_AGE_RANGE_GRID = CC.D_AGE_RANGE_GRID;
  var D_BREAK_PENALTY = CC.D_BREAK_PENALTY;
  var D_CONT_GATE = CC.D_CONT_GATE;
  var D_CONT_MAX = CC.D_CONT_MAX;
  var D_EMA_SLOPE_BARS = CC.D_EMA_SLOPE_BARS;
  var D_EMA_SLOPE_BONUS = CC.D_EMA_SLOPE_BONUS;
  var D_PATTERN_MAX = CC.D_PATTERN_MAX;
  var D_POS_FULL_CAP = CC.D_POS_FULL_CAP;
  var D_POS_MULT = CC.D_POS_MULT;
  var D_POS_PTS = CC.D_POS_PTS;
  var D_RAW_MAX = CC.D_RAW_MAX;
  var D_RES_PARALLEL_MAX = CC.D_RES_PARALLEL_MAX;
  var D_RES_PTS = CC.D_RES_PTS;
  var D_TOUCH_PTS = CC.D_TOUCH_PTS;
  var D_VOL_TOUCH_BONUS = CC.D_VOL_TOUCH_BONUS;
  var D_VOL_TOUCH_MULT = CC.D_VOL_TOUCH_MULT;
  var D_VOL_WINDOW = CC.D_VOL_WINDOW;
  var D_WIDTH_FRAC = CC.D_WIDTH_FRAC;
  var D_WIDTH_PENALTY = CC.D_WIDTH_PENALTY;
  var F3_RAIL_UNCHANGED_PCT = CC.F3_RAIL_UNCHANGED_PCT;
  var FIT_SCHEMA_VERSION = CC.FIT_SCHEMA_VERSION;
  var FIT_WINDOW = CC.FIT_WINDOW;
  var FIT_WINDOW_GRID = CC.FIT_WINDOW_GRID;
  var MIN_ANCHOR_SPAN = CC.MIN_ANCHOR_SPAN;
  var MIN_ANCHOR_SPAN_GRID = CC.MIN_ANCHOR_SPAN_GRID;
  var MIN_TOUCH_GAP = CC.MIN_TOUCH_GAP;
  var RECLAIM_BARS = CC.RECLAIM_BARS;
  var RES_RECENT_BARS = CC.RES_RECENT_BARS;
  var RES_RECENT_BARS_GRID = CC.RES_RECENT_BARS_GRID;
  var WEDGE_LOOKAHEAD = CC.WEDGE_LOOKAHEAD;
  var WEDGE_LOOKAHEAD_GRID = CC.WEDGE_LOOKAHEAD_GRID;
  var applyWickClip = CC.applyWickClip;
  var atr14 = CC.atr14;
  var bb3Reversion = CC.bb3Reversion;
  var bb3UpperReversion = CC.bb3UpperReversion;
  var buildPatternRecords = CC.buildPatternRecords;
  var bullEngulfing = CC.bullEngulfing;
  var bullEngulfingResearch = CC.bullEngulfingResearch;
  var clamp = CC.clamp;
  var computeLifecycle = CC.computeLifecycle;
  var computeRecentContainment = CC.computeRecentContainment;
  var computeResearchTol = CC.computeResearchTol;
  var detectChannel = CC.detectChannel;
  var emaLast = CC.emaLast;
  var emaState = CC.emaState;
  var entryEconomicsOf = CC.entryEconomicsOf;
  var executionContextOf = CC.executionContextOf;
  var findPivotsWindowed = CC.findPivotsWindowed;
  var fitIndependentResistance = CC.fitIndependentResistance;
  var isWedge = CC.isWedge;
  var makeFitId = CC.makeFitId;
  var multiSignalOnOneCandle = CC.multiSignalOnOneCandle;
  var passesAnchorSpacing = CC.passesAnchorSpacing;
  var railAt = CC.railAt;
  var rocketAtSupportResearch = CC.rocketAtSupportResearch;
  var scanBreaks = CC.scanBreaks;
  var signalConflict = CC.signalConflict;
  var threeInsideDown = CC.threeInsideDown;
  var threeInsideUp = CC.threeInsideUp;
  var threeInsideUpResearch = CC.threeInsideUpResearch;

  function detectStructureCore(candles, diag, meta) {
    if (!candles || candles.length < 30) return null;
    // A5 rejection diagnostics (Step 6 build review handoff format): when the caller passes a
    // diag object, count every rail-pair candidate that reached the anchor-spacing check and how
    // many of those passesAnchorSpacing() rejected, keyed by timeframe. Optional and additive -
    // detectChannelResearch's return value and every existing behavior are unaffected whether or
    // not diag is passed.
    var tf = meta.timeframe || '1d';
    if (diag) {
      if (!diag.a5) diag.a5 = {};
      if (!diag.a5[tf]) diag.a5[tf] = {checked:0, rejected:0};
    }
    var timeframe = meta.timeframe || '1d'; // A2: meta.timeframe absent -> default 1d/150 (no current production caller hits this - see plan §3)
    var windowSize = (timeframe === '4d-grid') ? FIT_WINDOW_GRID : FIT_WINDOW;
    var minAnchorSpan = (timeframe === '4d-grid') ? MIN_ANCHOR_SPAN_GRID : MIN_ANCHOR_SPAN;

    var rej = meta._rej || null;   // structure-core instrumentation: per-stage rejected-pair counts (never read by the search)
    var n = candles.length;
    // F3: which array each read below uses - structural reads of a bar's low/high (pivot selection,
    // the pivot's recorded price, containment) use the ANALYTIC copy `aCandles`; everything else
    // (ATR14, tol, ema, patterns, rocket, breaks/lifecycle, the fit's own `candles`) reads the RAW
    // `candles`. meta._noWickClip (harness only, never set by capture.js or the page) skips the clip
    // so the runner gets its OLD reading from this same function.
    var clipRes = meta._noWickClip ? null : applyWickClip(candles, n > windowSize ? n - windowSize : 0);
    var aCandles = clipRes ? clipRes.analytic : candles;
    var pv = findPivotsWindowed(aCandles, windowSize); // analytic: pivot selection + pivot price
    var highs = pv.highs, lows = pv.lows;
    // H3: meta._h3Exclude ({side, idx}, internal to this function's own re-fit below) drops one pivot.
    if (meta._h3Exclude) {
      var h3x = meta._h3Exclude;
      if (h3x.side === 'low') lows = lows.filter(function(pt){ return pt.idx !== h3x.idx; });
      else highs = highs.filter(function(pt){ return pt.idx !== h3x.idx; });
    }
    if (lows.length < 3 || highs.length < 1) return null;

    var price = candles[n-1].close;
    var tol = computeResearchTol(candles, price); // raw candles (F3: tol keeps the end-of-series ATR)
    var atr = atr14(candles);                     // raw candles

    var ema = emaState(candles);
    // E3 (Remediation spec, 2026-09-21/22): research-only sibling, reusing this same `atr`
    // (computed just above) - flag-off's own bullEngulfing(candles) call, in detectChannel
    // below, is untouched.
    var conf = {bb3:bb3Reversion(candles), bullEngulf:bullEngulfingResearch(candles, atr), threeInsideUp:threeInsideUpResearch(candles),
      bb3UpperReversion:bb3UpperReversion(candles), threeInsideDown:threeInsideDown(candles)};
    // E6 (Remediation spec, 2026-09-21/22): candle-level fact, not tied to any one rail-pair
    // candidate, so computed once here - before the rail-pair loop - and read by every
    // candidate's patternBonus below exactly the way patternN already reads conf today.
    // `rocket` isn't known yet (it needs the winning rail); the check is extended with it once
    // the winner is chosen, at the same point rocket/multi are computed below.
    var patternConflict = signalConflict([conf.bullEngulf, conf.threeInsideUp], [conf.bb3UpperReversion, conf.threeInsideDown]);

    var bestEligible = null, bestAny = null;

    for (var a = 0; a < lows.length-1; a++) {
      for (var b = a+1; b < lows.length; b++) {
        var p1 = lows[a], p2 = lows[b];
        var idxDelta = p2.idx - p1.idx;
        if (idxDelta < 3) continue;

        var slope = (p2.price - p1.price) / idxDelta;
        if (slope < -0.05 * p1.price / idxDelta) continue;

        var intercept = p1.price - slope * p1.idx;

        var supTouches = lows.filter(function(l) {
          var exp = railAt(slope,intercept,l.idx);
          return exp > 0 && Math.abs(l.price-exp)/exp <= tol;
        });
        // Step 6 build-review handoff (changed-row/cause table): optional per-pair diagnostic
        // log, keyed by the pair's full-series pivot indices + slope so a caller (regression-
        // runner's runResearch) can match a flag-off winning pair to its research-mode fate by
        // exact identity rather than guessing from output fields alone. `reached` records the
        // last gate this pair cleared before falling out of the loop (or 'full' if it became a
        // real candidate); null fields below simply were never computed for a pair that fell out
        // earlier. Zero effect on detection output - only appended to, never read, by this code.
        var pairLogEntry = null;
        if (diag) {
          if (!diag.pairLog) diag.pairLog = [];
          pairLogEntry = {p1idx:p1.idx, p2idx:p2.idx, slope:slope, touches:supTouches.length,
            reached:'touches', anchorPass:null, eligible:null, lifecycleState:null, score:null};
          diag.pairLog.push(pairLogEntry);
        }
        if (supTouches.length < 3) { if (rej) rej.touches++; continue; }

        // A5
        if (diag) diag.a5[tf].checked++;
        var anchorOk = passesAnchorSpacing(supTouches, minAnchorSpan, MIN_TOUCH_GAP);
        if (pairLogEntry) { pairLogEntry.anchorPass = anchorOk; if (anchorOk) pairLogEntry.reached = 'anchor'; }
        if (!anchorOk) {
          if (diag) diag.a5[tf].rejected++;
          if (rej) rej.anchorSpacing++;
          continue;
        }

        var firstIdx = Math.min.apply(null, supTouches.map(function(l){return l.idx;}));
        var lastIdx = n-1;
        var relHighs = highs.filter(function(h){return h.idx>=firstIdx;});
        if (!relHighs.length) continue;

        // B1: fit resistance independently first; B2 (recency-weighted parallel) is the fallback
        // only when no independent line clears 2+ touches with an agreeing slope.
        var resSlope, resIntercept, pivotHighs, resistanceFit;
        var resFit = fitIndependentResistance(highs, slope, intercept, firstIdx, tol, minAnchorSpan, MIN_TOUCH_GAP);
        if (resFit) {
          resSlope = resFit.slope; resIntercept = resFit.intercept;
          pivotHighs = resFit.touches; resistanceFit = 'independent';
        } else {
          var recentBars = (timeframe === '4d-grid') ? RES_RECENT_BARS_GRID : RES_RECENT_BARS;
          var relHighsRecent = relHighs.filter(function(h){ return h.idx >= n-recentBars; });
          if (!relHighsRecent.length) continue;
          var offsets = relHighsRecent.map(function(h){return h.price-railAt(slope,intercept,h.idx);}).filter(function(o){return o>0;});
          offsets.sort(function(x,y){return x-y;});
          if (!offsets.length) continue;
          var parallelChannelH = offsets[Math.floor(offsets.length/2)];
          if (parallelChannelH <= 0) continue;
          resSlope = slope; resIntercept = intercept + parallelChannelH;
          pivotHighs = []; resistanceFit = 'parallel';
        }

        // B1: wedge rejection - a pair whose rails cross inside the fit window, or converge
        // within the lookahead window past lastIdx, is not a channel.
        var lookahead = (timeframe === '4d-grid') ? WEDGE_LOOKAHEAD_GRID : WEDGE_LOOKAHEAD;
        if (isWedge(slope, intercept, resSlope, resIntercept, firstIdx, lastIdx+lookahead)) {
          if (pairLogEntry) pairLogEntry.reached = 'wedge';
          if (rej) rej.wedge++;
          continue;
        }

        var resTouches = relHighs.filter(function(h) {
          var exp = railAt(resSlope,resIntercept,h.idx);
          return exp > 0 && Math.abs(h.price-exp)/exp <= tol;
        });

        var supNow = railAt(slope,intercept,lastIdx);
        var resNow = railAt(resSlope,resIntercept,lastIdx);
        var channelH = resNow - supNow; // R3: height AT THE DECISION BAR - constant on the parallel path, time-varying on the independent path
        if (channelH <= 0) continue;
        var curPrice = candles[lastIdx].close;
        var position = (curPrice-supNow)/channelH; // B4: unclamped, same rationale as the flag-off path
        var distToRailPct = (curPrice-supNow)/curPrice; // B5

        var winCandles = aCandles.slice(firstIdx); // F3: fit-window length (containment in _noD mode judges a clipped bar at its ANALYTIC low/high)
        var inside = 0, containment;
        if (meta._noD) {
          for (var i=0; i<winCandles.length; i++) {
            var ci = firstIdx+i;
            var s = railAt(slope,intercept,ci);
            var r2 = railAt(resSlope,resIntercept,ci); // R3: both rails checked per bar, generalizes the old flat s+channelH
            if (winCandles[i].low >= s*(1-tol) && winCandles[i].high <= r2*(1+tol)) inside++;
          }
          containment = (inside/winCandles.length)*100;
          if (containment < 55) continue;
        } else {
          // Step 10 D: containment for the SCORE and the eligibility gate is measured on bar CLOSES (RAW candles;
          // a close is identical in the raw and analytic copies), same tol bands and both-rails-per-bar geometry.
          // The F3 analytic low/high containment above is now unused for score and gate (kept for _noD, for
          // aCandles' other readers: pivots, containmentRecent, the H3 re-fit).
          for (var ic=firstIdx; ic<=lastIdx; ic++) {
            var sC = railAt(slope,intercept,ic);
            var rC = railAt(resSlope,resIntercept,ic);
            if (candles[ic].close >= sC*(1-tol) && candles[ic].close <= rC*(1+tol)) inside++;
          }
          containment = (inside/winCandles.length)*100;
          if (containment < D_CONT_GATE) { if (rej) rej.containment++; continue; }
        }
        if (pairLogEntry) pairLogEntry.reached = 'containment';

        if (meta._capPosition && position > 0.75) continue;   // structure-core: the ONE difference - the cap exists only for the drift-guard test
        if (pairLogEntry) pairLogEntry.reached = 'position';

        // A1/H9
        // F3: breaks and lifecycle are close-based and read the RAW candles.
        var scan = scanBreaks(candles, slope, intercept, firstIdx, lastIdx, tol, !meta._noD);
        var lifecycle = computeLifecycle(scan, supTouches, candles, slope, intercept, lastIdx, tol, RECLAIM_BARS);

        var slopePct = (slope / Math.abs(railAt(slope,intercept,firstIdx)||1)) * 100;
        var invalidation = supNow * (1-tol);

        var score = 0, scoreBreakdown = null, ema50Slope = null;
        var patternN = (conf.bb3.hit?1:0) + (conf.bullEngulf.hit?1:0) + (conf.threeInsideUp.hit?1:0);
        var sa = Math.abs(slopePct);
        if (meta._noD) {
          // Step 10 D: meta._noD (harness only, never set by capture.js or the page) runs the PRE-D research block
          // verbatim, so the runner's OLD derives from this same function (the _noWickClip pattern).
          score += Math.min(25, supTouches.length*8);
          score += Math.min(15, resTouches.length*6);
          score += (containment/100)*20;
          if(slope >= 0) { score += sa>=0.05&&sa<=3?15:sa<0.05?8:Math.max(0,15-(sa-3)*3); }
          else { score += Math.max(0, 8-(sa*3)); }
          score += position<=0.33?10:position<=0.5?6:position<=0.66?3:0;
          score += Math.min(6, winCandles.length/20);
          if(sa > 5) score -= 10;
          if(slope < 0) score -= 5;
          score += ema.pts;
          // E6: patternBonus excluded from score when the candle-level pattern conflict is present.
          var patternBonus = (patternN > 0 && !patternConflict) ? (2*patternN - 1) : 0;
          score += patternBonus;
          score = Math.round(clamp(score,0,100));
        } else {
          // Step 10 D. Read sources per component: everything below reads RAW candles / fit locals; the F3 analytic
          // copy is not consulted by the score (containment above is on raw closes).
          var dSlopePts = 0;
          if (slope >= 0) { dSlopePts = sa>=0.05&&sa<=3?15:sa<0.05?8:Math.max(0,15-(sa-3)*3); }
          else { dSlopePts = Math.max(0, 8-(sa*3)); }
          var dTouch = D_TOUCH_PTS[clamp(supTouches.length,2,7)-2];
          var dRes = D_RES_PTS[Math.min(resTouches.length,3)];
          if (resistanceFit === 'parallel') dRes = Math.min(dRes, D_RES_PARALLEL_MAX);
          var dCont = clamp((containment - D_CONT_GATE) / (100 - D_CONT_GATE) * D_CONT_MAX, 0, D_CONT_MAX);
          var dPos = (distToRailPct <= Math.min(D_POS_MULT[0]*tol, D_POS_FULL_CAP)) ? D_POS_PTS[0]
            : (distToRailPct <= D_POS_MULT[1]*tol) ? D_POS_PTS[1] : D_POS_PTS[2];
          var ageR = (timeframe === '4d-grid') ? D_AGE_RANGE_GRID : D_AGE_RANGE, ageBars = winCandles.length, dAge;
          if (ageBars > ageR[2] || ageBars <= ageR[0]) dAge = 0;
          else if (ageBars >= ageR[1]) dAge = D_AGE_MAX;
          else dAge = D_AGE_MAX * (ageBars - ageR[0]) / (ageR[1] - ageR[0]);
          // ema50Slope (C1's definition): (ema50[n-1] - ema50[n-1-N]) / ema50[n-1-N]. emaLast over a prefix is the same
          // fold, so it is bitwise the series value at that index. null when there are <= N closes or a non-positive base.
          if (n > D_EMA_SLOPE_BARS) {
            var e50Prev = emaLast(candles.slice(0, n - D_EMA_SLOPE_BARS).map(function(c){return c.close;}), 50);
            if (e50Prev > 0) ema50Slope = (ema.e50 - e50Prev) / e50Prev;
          }
          var dEmaSlope = (ema50Slope !== null && ema50Slope > 0) ? D_EMA_SLOPE_BONUS : 0;
          // Pattern bonus: 1D only; E6 conflict already excluded via patternConflict; shape 1/3/3.
          var dPattern = (timeframe === '1d' && patternN > 0 && !patternConflict) ? Math.min(D_PATTERN_MAX, 2*patternN - 1) : 0;
          // Volume on the most recent support touch bar vs the mean of the D_VOL_WINDOW bars before it (exclusive).
          // Missing / non-finite / non-positive volume in any of those bars, or too few prior bars -> 0, never a throw.
          var dVol = 0, volTouch = null;
          var tIdx = -1; for (var vt=0; vt<supTouches.length; vt++) if (supTouches[vt].idx > tIdx) tIdx = supTouches[vt].idx;
          if (tIdx >= D_VOL_WINDOW) {
            var vTouch = candles[tIdx].volume, vSum = 0, vOk = (typeof vTouch === 'number' && isFinite(vTouch) && vTouch > 0);
            for (var vk=tIdx-D_VOL_WINDOW; vOk && vk<tIdx; vk++) {
              var vv = candles[vk].volume;
              if (typeof vv === 'number' && isFinite(vv) && vv > 0) vSum += vv; else vOk = false;
            }
            if (vOk) { var vMean = vSum / D_VOL_WINDOW; volTouch = {idx:tIdx, volume:vTouch, mean20:vMean, ratio:vTouch / vMean}; if (vTouch >= D_VOL_TOUCH_MULT * vMean) dVol = D_VOL_TOUCH_BONUS; }
          }
          var dBreak = D_BREAK_PENALTY * scan.runCount2;
          var widthFrac = channelH / curPrice, dWidth = widthFrac > D_WIDTH_FRAC[1] ? D_WIDTH_PENALTY[1] : widthFrac > D_WIDTH_FRAC[0] ? D_WIDTH_PENALTY[0] : 0;
          var dSlopeSteep = sa > 5 ? 10 : 0, dSlopeNeg = slope < 0 ? 5 : 0;
          var rawPositive = dTouch + dRes + dCont + dSlopePts + dPos + dAge + ema.pts + dEmaSlope + dPattern + dVol;
          var rescaled = rawPositive * 100 / D_RAW_MAX; // the ONE rescale; penalties below are absolute points
          var penaltyTotal = dBreak + dWidth + dSlopeSteep + dSlopeNeg;
          score = Math.round(clamp(rescaled - penaltyTotal, 0, 100));
          scoreBreakdown = {touch:dTouch, res:dRes, cont:dCont, slope:dSlopePts, pos:dPos, age:dAge, ema:ema.pts, emaSlope:dEmaSlope,
            pattern:dPattern, vol:dVol, rawPositive:rawPositive, rescaled:rescaled,
            penalties:{brk:dBreak, width:dWidth, slopeSteep:dSlopeSteep, slopeNeg:dSlopeNeg}, penaltyTotal:penaltyTotal,
            final:score, runCount2:scan.runCount2, volTouch:volTouch};
        }

        var eligible = (lifecycle.state === 'intact' || lifecycle.state === 're-qualified');
        if (pairLogEntry) {
          pairLogEntry.reached = 'full'; pairLogEntry.eligible = eligible;
          pairLogEntry.lifecycleState = lifecycle.state; pairLogEntry.score = score;
        }
        var candidate = {
          score:score, supportTouches:supTouches.length, resTouches:resTouches.length,
          containment:Math.round(containment), slope:slopePct, position:position,
          supportNow:supNow, resistNow:resNow, invalidation:invalidation, channelH:channelH,
          distToRailPct:distToRailPct, // B5
          resSlope:resSlope, resIntercept:resIntercept, pivotHighs:pivotHighs, resistanceFit:resistanceFit, // B1/R3
          candles:candles.slice(-150), pivotLows:supTouches,
          supSlope:slope, supIntercept:intercept, firstIdx:firstIdx, lastIdx:lastIdx,
          isAscending:slope>=0, isFlat:Math.abs(slopePct)<0.1,
          emaState:ema.state, ema21:ema.e21, ema50:ema.e50, emaPts:ema.pts,
          bb3:conf.bb3.hit, bullEngulf:conf.bullEngulf.hit, threeInsideUp:conf.threeInsideUp.hit,
          bb3Trigger:conf.bb3, bullEngulfTrigger:conf.bullEngulf, threeInsideUpTrigger:conf.threeInsideUp,
          bb3UpperReversion:conf.bb3UpperReversion.hit, threeInsideDown:conf.threeInsideDown.hit,
          bb3UpperReversionTrigger:conf.bb3UpperReversion, threeInsideDownTrigger:conf.threeInsideDown,
          fitId: makeFitId(meta.coinId, meta.timeframe, meta.source, candles[lastIdx].time, firstIdx, lastIdx),
          timeframe: meta.timeframe || null,
          candleSource: meta.source || null,
          lookback: Math.min(n, windowSize),
          fitStartTime: candles[firstIdx].time,
          fitEndTime: candles[lastIdx].time,
          schemaVersion: FIT_SCHEMA_VERSION,
          detectorVersion: DETECTOR_VERSION,
          containmentFull: Math.round(containment),
          containmentRecent: computeRecentContainment(aCandles, slope, intercept, channelH, firstIdx, lastIdx), // F3: containment -> ANALYTIC copy
          touchEvents: supTouches,
          pivotIds: supTouches.map(function(t){ return t.time; }),
          nearestResistance: resNow,
          detectionPrice: curPrice,
          detectionAsOf: candles[lastIdx].time,
          lifecycleState: lifecycle.state,
          maxBreakRun: lifecycle.maxBreakRun,
          lastBreakIdx: lifecycle.lastBreakIdx,
          barsSinceBreak: lifecycle.barsSinceBreak,
          tol: tol,
          atr14: atr,
          research: true,
          breachHistory: []
        };
        if (scoreBreakdown) { candidate.scoreBreakdown = scoreBreakdown; candidate.ema50Slope = ema50Slope; candidate.breakRunCount2 = scan.runCount2; } // Step 10 D (absent under _noD)
        if (scan.runs) candidate.breakRuns = scan.runs; // Step 12-A (G5): break runs with times, research only (absent under _noD)

        if (eligible && (!bestEligible || candidate.score > bestEligible.score)) bestEligible = candidate;
        if (!bestAny || candidate.score > bestAny.score) bestAny = candidate;
      }
    }

    var winner = bestEligible || bestAny; // R1: eligible pair preferred; else best-scoring pair carries its ineligible state
    if (!winner) return null;

    var rocket = rocketAtSupportResearch(candles, winner.supSlope, winner.supIntercept, tol, atr, winner.lifecycleState);
    var bb3Coincidence = conf.bb3.hit ? {hit:true, idx:n-1, time:candles[n-1].time} : conf.bb3;
    var multi = multiSignalOnOneCandle([bb3Coincidence, conf.bullEngulf, conf.threeInsideUp, rocket]);
    winner.rocket = rocket.hit;
    winner.rocketTrigger = rocket;
    winner.multiSignal = multi.hit;
    winner.multiSignalTrigger = multi;

    // E6: extend the candle-level conflict with `rocket`, now that it's known (rail-dependent,
    // only available post-winner) - reuses patternConflict when bullEngulf/threeInsideUp already
    // found a conflicting pair, otherwise checks rocket alone against the same bearish set.
    var conflict = patternConflict || signalConflict([rocket], [conf.bb3UpperReversion, conf.threeInsideDown]);
    winner.conflictingSignals = !!conflict;
    winner.conflictingSignalsPair = conflict;

    // H11: one inspectable record per fired pattern (see buildPatternRecords above).
    winner.patternRecords = buildPatternRecords(candles, conf, rocket, conflict, meta, tol, winner.lifecycleState);

    // F3 / H3: every clipped bar in the fit window, one entry per clipped side, plus the H3 sensitivity
    // read: re-run this same fit with that pivot excluded and report the rail delta (percent, signed:
    // (without - with) / with * 100). Low side -> support rail (supportNow); high side -> resistance rail
    // (resistNow), only when the winner's resistance is an independent fit (B1) - a parallel resistance is
    // derived from the support line, so there is no separate pivot to exclude (reason 'parallel').
    // reason: null (computed) | 'not-pivot' | 'parallel' | 'no-fit-without-pivot' | 'no-base'.
    // Raw candles stay untouched: the entry carries raw and clippedTo, the analytic copy is never exposed.
    var wickClips = [];
    if (clipRes) {
      for (var wi = 0; wi < clipRes.clips.length; wi++) {
        var wc = clipRes.clips[wi];
        var isPivot = (wc.side === 'low' ? lows : highs).some(function(pt){ return pt.idx === wc.idx; });
        var wEntry = {idx:wc.idx, time:wc.time, side:wc.side, raw:wc.raw, clippedTo:wc.clippedTo, atr:wc.atr,
          pivot:isPivot, railDeltaPct:null, railUnchanged:null, reason:null};
        if (!isPivot) wEntry.reason = 'not-pivot';
        else if (wc.side === 'high' && winner.resistanceFit !== 'independent') wEntry.reason = 'parallel';
        else if (!meta._noH3) {
          var refit = detectStructureCore(candles, null, Object.assign({}, meta, {_h3Exclude:{side:wc.side, idx:wc.idx}, _noH3:true, _rej:null}));
          var rBase = (wc.side === 'low') ? winner.supportNow : winner.resistNow;
          if (!refit) wEntry.reason = 'no-fit-without-pivot';
          else if (!(rBase > 0)) wEntry.reason = 'no-base';
          else {
            var rAlt = (wc.side === 'low') ? refit.supportNow : refit.resistNow;
            wEntry.railDeltaPct = (rAlt - rBase) / rBase * 100;
            wEntry.railUnchanged = Math.abs(wEntry.railDeltaPct) < F3_RAIL_UNCHANGED_PCT;
          }
        }
        wickClips.push(wEntry);
      }
    }
    winner.wickClips = wickClips;

    // Step 11-B (H6): entry economics from the fit + the windowed pivot highs (full-series idx) - never re-indexed downstream.
    winner.entryEconomics = entryEconomicsOf(winner, highs);
    // Step 11-D (H10): execution context on the RAW series (last closed bar = trigger bar). Descriptive; no gate reads it.
    winner.executionContext = executionContextOf(winner, candles);

    return winner;
  }

  // --- Channel detection (scoring + per-coin diag) ---
  // H7: OPTIONAL third arg `meta` ({coinId, timeframe, source}) - see header note. Every
  // existing 2-arg caller is unaffected (meta defaults to {}).
  // Step 6 (2026-09-22): meta.research===true routes to detectChannelResearch above INSTEAD of
  // the body below - a per-call dispatch (R3: no module-level RESEARCH_MODE), so the body below
  // is completely unmodified source and the flag-off output is unaffected by this change by
  // construction, not by discipline.

  var STRUCTURE_VERSION = 'structure-core-1 (channel-core ' + CC.DETECTOR_VERSION + ')';
  var COPIED_FROM_SHA1 = '089941eefa1e9cece82bf8b172572a929508b1ab';
  // detectStructure: the winner tagged structural, or null. `out` (optional) receives the per-stage rejected-pair counts of this search even when the result is null.
  function detectStructure(candles, meta, out) {
    meta = meta || {};
    var rej = {anchorSpacing: 0, wedge: 0, touches: 0, containment: 0, position: 0};
    var m = Object.assign({}, meta, {research: true, _rej: rej});
    var fit = detectStructureCore(candles, null, m);
    if (out) out.rejections = rej;
    if (!fit) return null;
    var p = fit.position, band = (typeof p === 'number' && p > 1) ? 'above-resistance' : ((typeof p === 'number' && p > 0.75) ? 'upper' : null), lt = null;
    (fit.touchEvents || []).forEach(function (t) { var tm = (t && typeof t.time === 'number') ? t.time : null; if (tm != null && (lt == null || tm > lt)) lt = tm; });
    return Object.assign({}, fit, {structural: true, positionBand: band, lastTouchTime: lt, rejections: rej});
  }
  return {detectStructure: detectStructure, detectStructureCore: detectStructureCore, STRUCTURE_VERSION: STRUCTURE_VERSION, COPIED_FROM_SHA1: COPIED_FROM_SHA1, COPIED_TEXT_SOURCE: 'channel-core.js detectChannelResearch'};
});
